AWSTemplateFormatVersion: 2010-09-09
Description: Checkpoint CloudFormation

Parameters:

  Name:
    Default: noora




Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup

  Properties:
    GroupDescription: nooran-securitygroup
    VpcId: vpc-32cc224b
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
